<script setup>
import { onMounted, ref } from 'vue'
import { getHealth, getHome } from '../api'
const user = ref(JSON.parse(localStorage.getItem('microworld-user') || 'null'))
const healthy = ref(false); const text = ref('小说将在这里分叉、生长、合流。')
onMounted(async () => { try { const [health, home] = await Promise.all([getHealth(), getHome()]); healthy.value = health.status === 'UP'; text.value = home.message } catch { text.value = '暂时无法连接后端服务，请先启动 Spring Boot。' } })
function logout() { localStorage.removeItem('microworld-user'); localStorage.removeItem('microworld-token'); user.value = null }
</script>
<template><main><nav class="nav container"><RouterLink class="brand" to="/"><span>✦</span> Your Microworld</RouterLink><div class="nav-actions"><div class="status"><i :class="{ on: healthy }"></i>{{ healthy ? '服务在线' : '连接中' }}</div><button v-if="user" class="text-button" @click="logout">退出登录</button><RouterLink v-else class="nav-login" to="/login">登录</RouterLink></div></nav><section class="hero container"><div class="hero-copy"><p class="eyebrow">协作式叙事图谱</p><h1>每一个选择，<br><em>都值得成为一条故事线。</em></h1><p class="intro">{{ text }}</p><div class="pills"><span>主线协作</span><span>IF 分支</span><span>段落评论</span></div><div class="hero-actions"><RouterLink v-if="!user" class="hero-button" to="/register">开始创作</RouterLink><span v-else>欢迎回来，{{ user.username }}。</span></div></div><section class="welcome-card"><span class="avatar">{{ user ? user.username.slice(0, 1).toUpperCase() : '✦' }}</span><p class="eyebrow">{{ user ? '已完成 JWT 认证' : 'SPRINT 0 已就绪' }}</p><h2>{{ user ? user.username : '故事从这里开始' }}</h2><p>{{ user ? '你的访问令牌已保存在当前浏览器。' : '注册后即可获得访问令牌，开始阅读、评论与共创。' }}</p><RouterLink v-if="!user" class="outline-link" to="/login">登录账户</RouterLink></section></section><section class="features container"><article><b>01</b><h3>主线接力</h3><p>用竞标和投票决定下一章由谁续写。</p></article><article><b>02</b><h3>平行 IF 线</h3><p>从章节节点分叉，探索另一种选择的后果。</p></article><article><b>03</b><h3>段落级共鸣</h3><p>把讨论准确地留在触发它的那一段文字旁。</p></article></section></main></template>
